[WIP] Play over the Web
marmelab/15-puzzle-go pull request #8
Opened 2017-10-27 11:33 UTC by Luwangel

- [x] Create a webserver with routes new, move, suggest
- [x] Update the docker to expose the port
- [] Update the Readme

2017-10-27 12:12 UTC, jpetitcolas requested changes
Don't forget tests.

2017-10-27 12:12 UTC, jpetitcolas commented on Dockerfile
> +EXPOSE 2000
Not sure you need that.

2017-10-27 12:12 UTC, jpetitcolas commented on src/webserver/webserver.go
> +	http.HandleFunc("/move", Move)
You should restrict routes using correct HTTP actions. Here for instance, you need a `POST` only route.

2017-10-27 12:12 UTC, jpetitcolas commented on src/webserver/routes.go
> +	decoder := json.NewDecoder(r.Body)
You should check `r.Method`. This route should be accessible only via GET.

2017-10-27 14:26 UTC, jpetitcolas requested changes

2017-10-27 14:26 UTC, jpetitcolas commented on src/webserver/webserver.go
> +	r.HandleFunc("/suggest", Suggest).Methods("POST")
GET

2017-10-27 14:26 UTC, jpetitcolas commented on src/webserver/routes.go
> +	fmt.Println("Route 'suggest' called")
Debug spotted

2017-10-27 14:26 UTC, jpetitcolas commented on src/webserver/routes.go
> +	SolvedGrid [][]int
Rename to `initialGrid`

2017-10-27 14:26 UTC, jpetitcolas commented on src/webserver/routes.go
> +	path, err := game.DeepPuzzleAlgorithm(grid, solvedGrid)
I would name it `SolvePuzzle`

2017-10-27 14:26 UTC, jpetitcolas commented on src/webserver/routes.go
> +	w.Header().Set("Content-Type", "application/json")
Can't we factorize it in a dedicated middleware?

2017-10-30 14:38 UTC, jdemangeon commented on src/webserver/routes.go
> +	queryString := r.URL.Query().Get("size")
It's size, not queryString

2017-10-30 14:43 UTC, jdemangeon commented on src/webserver/routes.go
> +		panicOnError(errors.New("No suggestion found"))
I'll use a 404 instead of 500 here. It'll help you when implementing client (check on status code is better than check on string).

2017-10-31 08:14 UTC, merged